services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arch-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - arch-db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - local.env

  # make-migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - local.env
  #   command: sh -c "
  #     export PYTHONPATH=$(pwd) && \
  #     cd /app/db && \
  #     alembic revision --autogenerate"

  # migrate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - local.env
  #   command: sh -c "
  #     export PYTHONPATH=$(pwd) && \
  #     cd /app/db && \
  #     alembic upgrade head"

volumes:
  arch-db-data:
